<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingPlatform.Api\TradingPlatform.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.2.3" />
  </ItemGroup>

</Project>

