<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\TradingPlatform.Domain\TradingPlatform.Domain.csproj" />
    <ProjectReference Include="..\..\Core\TradingPlatform.Application\TradingPlatform.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RulesEngine" Version="5.0.3" />
    <PackageReference Include="Skender.Stock.Indicators" Version="2.5.0" />
  </ItemGroup>

</Project>
